config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :title, :recipe_type, :cuisine, :difficulty, :cook_time, 
              :ingredients, :cook_method, presence: true

    def cook_time_min
        cook_time.to_s + ' minutos'
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @recipes = Recipe.all
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def recipe_params
        params.require(:recipe).permit(:title, :recipe_type, :cuisine, :difficulty, :cook_time, :ingredients, :cook_method)
    end

    def show
        @recipe = Recipe.find(params[:id])
    end

    def new 
        @recipe = Recipe.new
    end
    
    def create
        @recipe = Recipe.new recipe_params

        if @recipe.save
            redirect_to @recipe
        else
            flash[:notice] = "Você deve informar todos os dados da receita"
            render :new
        end 
    end 

    def edit
        @recipe = Recipe.find params[:id]
    end 

    def update
        @recipe = Recipe.find params[:id]

        if @recipe.update(recipe_params)
            redirect_to @recipe
        else
            flash[:notice] = "Você deve informar todos os dados da receita"
            render :edit
        end
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>CookBook</h1>
<p>Bem-vindo ao maior livro de receitas online</p>

<%= link_to 'Home', root_path, class: 'nav-link' %>
<%= link_to 'Enviar uma receita', new_recipe_path, class: 'nav-link' %>

<%@recipes.each do |recipe|%>
    <h1><%= link_to recipe.title, recipe %></h1>
    <ul>
        <li><%= recipe.recipe_type %></li>
        <li><%= recipe.cuisine %></li>
        <li><%= recipe.difficulty %></li>
        <li><%= recipe.cook_time_min %></li>
    </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookbookJonatas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<h1>Editar Receita</h1>

<%= flash[:notice] %>

<%= form_for @recipe do |f| %>
    <div>
        <%= f.label :title, 'Título' %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :recipe_type, 'Tipo da Receita' %>
        <%= f.text_field :recipe_type %>
    </div>
    <div>
        <%= f.label :cuisine, 'Cozinha' %>
        <%= f.text_field :cuisine %>
    </div>
    <div>
        <%= f.label :difficulty, 'Dificuldade' %>
        <%= f.text_field :difficulty %>
    </div>
    <div>
        <%= f.label :cook_time, 'Tempo de Preparo' %>
        <%= f.number_field :cook_time %>
    </div>
    <div>
        <%= f.label :ingredients, 'Ingredientes' %>
        <%= f.text_area :ingredients %>
    </div>
    <div>
        <%= f.label :cook_method, 'Como Preparar' %>
        <%= f.text_area :cook_method %>
    </div>
    <div>
        <%= f.submit 'Enviar' %>
    </div>
<% end %>

app/views/recipes/new.html.erb
<h1>Cadastra Receita</h1>

<%= flash[:notice] %>

<%= form_for @recipe do |f| %>
    <div>
        <%= f.label :title, 'Título' %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :recipe_type, 'Tipo da Receita' %>
        <%= f.text_field :recipe_type %>
    </div>
    <div>
        <%= f.label :cuisine, 'Cozinha' %>
        <%= f.text_field :cuisine %>
    </div>
    <div>
        <%= f.label :difficulty, 'Dificuldade' %>
        <%= f.text_field :difficulty %>
    </div>
    <div>
        <%= f.label :cook_time, 'Tempo de Preparo' %>
        <%= f.number_field :cook_time %>
    </div>
    <div>
        <%= f.label :ingredients, 'Ingredientes' %>
        <%= f.text_area :ingredients %>
    </div>
    <div>
        <%= f.label :cook_method, 'Como Preparar' %>
        <%= f.text_area :cook_method %>
    </div>
    <div>
        <%= f.submit 'Enviar' %>
    </div>
<% end %>

app/views/recipes/show.html.erb
<h1>Receita</h1>

<h1><%= @recipe.title %></h1>

<h3>Detalhes</h3>
<p><%= @recipe.recipe_type %></p>
<p><%= @recipe.cuisine %></p>
<p><%= @recipe.difficulty %></p>
<p><%= @recipe.cook_time_min %></p>

<h3>Ingredientes</h3>
<p><%= @recipe.ingredients %></p>

<h3>Como Preparar</h3>
<p><%= @recipe.cook_method %></p>

<%= link_to 'Voltar', root_path, class: 'btn btn-secondary' %>
<%= link_to 'Editar', edit_recipe_path(@recipe), class: 'btn btn-primary' %>